version: '3.8'

services:
  mypostgres:
    image: postgres:latest
    container_name: java-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: postgres
